- setup.sh
> setup.sh: enable the download of releases

- setup.sh
> setup.sh: avoid creating recursive links to "./files"

- README.md
- deploy-all.yml
- deploy-knox.yml
- inventory/group_vars/knox.yml
> playbooks: add knox

- README.md
- deploy-hdfs.yml
- inventory/group_vars/all.yml
- setup.sh
- tdp-release-uris
- test-cluster-deployment.yml
> Fixes and improvements

- README.md
- deploy-hdfs.yml
- inventory/group_vars/all.yml
- setup.sh
- tdp-release-uris
- test-cluster-deployment.yml
> Fixes and setup improvements

- tdp-release-uris
> setup.sh: fix solr .tar.gz url

- deploy-all.yml
- deploy-exporter.yml
> exporter: add jmx-exporter

- tdp-release-uris
> setup.sh: add knox dist

- scripts/tdp-release-uris.txt
> fix: add ranger knox plugin to release file

- scripts/setup.sh
- scripts/tdp-release-uris.txt
Fixes  #61
Three commits reflect discussion of fix with @Nuttymoon.
> Fix setup script symbolic links

- README.md
> README.md: fix bash commands + add some docs

- README.md
- deploy-ca.yml
- deploy-hive.yml
- deploy-kerberos.yml
- deploy-ldap-kerberos.yml
- deploy-postgres.yml
- deploy-ranger.yml
- deploy-users.yml
- deploy-vms.yml
- generate-node-deployment-config.yml
- scripts/setup.sh
> Correct tdp_extra collection dir + use git clone with https instead of ssh

- test-cluster-deployment.yml
> fix: move tasks to where tdp_user can kinit

- README.md
> docs(readme.md): update requirements

- scripts/setup.sh
- scripts/tdp-release-uris.txt
> refactor: remove unecessary loop

- README.md
- deploy-livy.yml
- inventory/group_vars/all.yml
- scripts/git-commit-download.sh
- scripts/setup.sh
- scripts/tdp-release-uris.txt
Fixes #75 
This PR depends on https://github.com/TOSIT-IO/tdp-collection-extras/pull/16
> livy: add deployment

- README.md
> doc: add command to install base box if required

- README.md
> README.md: mark jq as requirement

- scripts/tdp-release-uris.txt
Fixes #103 
- [x ] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.
> fix: change solr download link

- scripts/tdp-release-uris.txt
> Adding Apache NiFi

- scripts/tdp-release-uris.txt
Reverts TOSIT-IO/tdp-getting-started#87
> Revert "Adding Apache NiFi"

- README.md
- deploy-all.yml
- deploy-spark3.yml
- scripts/setup.sh
- scripts/tdp-release-uris.txt
Fixes #95 
Depends on:
- https://github.com/TOSIT-IO/tdp-collection/pull/259
- https://github.com/TOSIT-IO/tdp-collection-extras/pull/19
> feat: add spark3

- deploy-service-start-on-boot-policies.yml
> fix: add hbase services to playbook

- README.md
- scripts/git-commit-download.sh
- scripts/setup.sh
> Setup stable latest flags #97

- deploy-kerberos.yml
- deploy-users.yml
> Fix fetch tasks #99

- deploy-exporter.yml
- deploy-hadoop.yml
- deploy-hbase.yml
- deploy-hdfs.yml
- deploy-hive.yml
- deploy-knox.yml
- deploy-ranger.yml
- deploy-spark.yml
- deploy-spark3.yml
- deploy-yarn.yml
- deploy-zookeeper.yml
> playbook: use meta playbooks generated by tdp-lib

- README.md
- deploy-livy-spark3.yml
- deploy-livy.yml
- deploy-livyspark3.yml
- deploy-service-start-on-boot-policies.yml
- inventory/group_vars/all.yml
- scripts/setup.sh
- scripts/tdp-release-uris.txt
Fixes #125 
Depends on:
- https://github.com/TOSIT-IO/tdp-collection-extras/pull/41
> Add Livy for Spark 3 deployment

- deploy-kafka.yml
- deploy-users.yml
- inventory/group_vars/all.yml
- inventory/group_vars/ca.yml
- scripts/tdp-release-uris.txt
Fixes #139 
Depends on:
- #136 
- https://github.com/TOSIT-IO/tdp-collection-extras/pull/43
This PR adds the creation of the SSL certificate for the Ranger Kafka plugin and the Ranger Kafka policy for `tdp_user`. It also renames other `tdp_user` Ranger policies for better readability and coherence.
> Ranger Kafka plugin deployment

- scripts/tdp-release-uris.txt
> fix: added ranger-kms to the releases download list

- inventory/group_vars/hive_client.yml
- inventory/group_vars/hive_s2.yml
- test-cluster-deployment.yml
Fixes #133 
- Modified test-cluster-deployment.yml to handle the database creation after the change
- Deleted unnecessary ranger policy related to this topic.
I'll modify this to use external tables next.
> feat(hive): enable hive impersonation

- .gitignore
- .gitmodules
- README.md
- scripts/setup.sh
- https://github.com/TOSIT-IO/tdp-getting-started/issues/117
Fixes #117
> refactor(submodules): Use git submodules

- .gitignore
- README.md
- requirements.txt
- scripts/setup.sh
Refactor setup script with functions.
Add "-e" option to enable feature like "extras".
Add python venv setup.
Fixes #153 #151 
> Refactor and add an option to setup script to enable feature

- inventory/group_vars/all.yml
> feat: set config_tdp_getting_started to true to allow connections

- scripts/setup.sh
> fix(setup): refresh collections commit hashed

- deploy-spark.yml
- deploy-spark3.yml
> fix: add livy deployment to deploy-spark and deploy-spark3

- deploy-all.yml
- scripts/tdp-release-uris.txt
> fix(setup): add hbase-spark JAR to the release list

- README.md
- requirements.txt
Fixes no issue
This means you need to install the dependency from requirements.txt. But `scripts/setup.sh` does it, therefore it should not be a problem.
> feat: add mitogen to accelerate deployments

- .gitignore
- scripts/setup.sh
> Add "-c" option for "clean" the working directory

- scripts/setup.sh
> fix(setup): use "git submodule status" to check if submodule exists

- .gitmodules
- README.md
- scripts/setup.sh
Fixes #152 
With this PR, the `setup.sh` script will checkout `tdp-lib` via git submodule and install it via `pip install -e` to be able to develop the `tdp-lib` with the getting started if needed.
> Add tdp-lib for deploying TDP

- .gitmodules
- README.md
- ansible.cfg
- scripts/git-commit-download.sh
- scripts/setup.sh
> feat: remove 2 useless directories for Ansible collections

- README.md
- requirements.txt
Adding to the README to use the requirements file for supported version.
Fixes #184 
> fix: mitogen version should be <0.3 and >0.2.9

- tdp_vars_overrides/hive/hive.yml
> fix(hive): update following hive refactor

- README.md
> docs: correct beeline documentation

- README.md
> fix: update hbase snippet in readme

- README.md
- scripts/tdp-release-uris.txt
- tdp_vars_overrides/jupyterhub/jupyterhub.yml
Make sure to have run `scripts/setup.sh -c`. Because there is variable overloading for `hadoop`'s core site and for `ranger`'s kms-site.
Requires:
> feat: add jupyterhub to tdp-getting-started

- .gitignore
> chore: ignore environment related files

- inventory/group_vars/all.yml
> feat: add knox ranger policy for tdp_user

- .gitignore
- ansible.cfg
- inventory/tdp_vars.yaml
- scripts/setup.sh
> feat: configure use of new inventory plugin

- .gitmodules
- README.md
- scripts/setup.sh
Add documentation to run tdp-server and deploy TDP with it.
Fixes #226
> feat: add tdp-server as git submodule

- .gitmodules
- README.md
- requirements.txt
- scripts/setup.sh
Fixes #228 
Marking as draft waiting for https://github.com/TOSIT-IO/tdp-observability/pull/20 to be merged. I will update the submodule when it is done.
> feat: add tdp-observability

- .gitignore
- .gitmodules
- README.md
- scripts/setup.sh
Add documentation to run tdp-ui and deploy TDP with it.
Fixes #234
> feat(tdp-ui): add tdp-ui as git submodule

- tdp_vars_overrides/jupyterhub/jupyterhub.yml
> jupyterhub: add postgres port in database connexion

- tdp_vars_overrides/hue/hue.yml
> feat: add hue vars to tdp_vars_overrides

- scripts/setup.sh
> fix(setup): escape double quote for BACKEND_CORS_ORIGINS variable

- scripts/tdp-release-uris.txt
Fix: https://github.com/TOSIT-IO/hbase/issues/2
>  fix(releases-uris): add hbase-hbck2 JAR

- scripts/tdp-release-uris.txt
Fixes #261 
Related to the following PR: https://github.com/TOSIT-IO/tdp-observability/pull/38
> feat: add postgres_exporter

- tdp_vars_overrides/jupyterhub/jupyterhub.yml
> fix: rename postgres variable

- scripts/setup.sh
- scripts/tdp-release-uris.txt
> feat: add prometheus loki promtail grafana release

- scripts/setup.sh
Fixes #290 
ansible-galaxy: command not found
Source the Python venv before running the `ansible-galaxy` command.
> fix(dev): fix ansible collections install

- .gitignore
Fixes None
Ignore `.python-version` file from project (used to specify a local python version with pyenv).
> chore: prevent git from tracking pyenv files

- scripts/tdp-release-uris.txt
Fixes None
Following https://github.com/TOSIT-IO/tdp-collection-extras/pull/149, update hue release URL.
> Fix hue release url

- README.md
> docs: update common requirements for python

- README.md
Fixes none
Following [the discussion](https://github.com/orgs/TOSIT-IO/discussions/92)
> docs: fix namings

- ansible.cfg
Fixes None
Force Ansible colored output by default.
> feat: force ansible color by default

- tdp_vars_overrides/hive/hive.yml
- tdp_vars_overrides/ranger/ranger.yml
Fixes None
Ports should default to `tdp_cluster` var `postgresql_server_port`
> fix: postgres port tdp_cluster

- scripts/setup.sh
- scripts/tdp-release-uris.json
> Feat downloads management

- scripts/tdp-release-uris.json
- scripts/tdp-release-uris.txt
> feat: upgrade grafana
